const {JSDOM}=require('jsdom');
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../static/index.html'),'utf8');
const script=fs.readFileSync(path.join(__dirname,'../static/campus-home.js'),'utf8');
const rooms=[{id:1,title:'Garden room',campus:'University of Limpopo',is_available:true,monthly_rent:1800},{id:2,title:'Filled room',campus:'University of Limpopo',is_available:false},{id:3,title:'City room',campus:'Other College',is_available:true}];
const ads=[{id:1,headline:'Campus shuttle',campus:'University of Limpopo',category:'Ride & transport'},{id:2,headline:'Biology textbooks',campus:'University of Limpopo',category:'Sales & retail',description:'<img src=x onerror=alert(1)>',website_url:'javascript:alert(1)'},{id:3,headline:'Math tutoring',campus:'Other College',category:'Tutoring'}];
async function setup(failed=[]){const dom=new JSDOM(html,{url:'https://campus.test/',runScripts:'outside-only'});const w=dom.window;w.AbortSignal=AbortSignal;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.fetch=async url=>({ok:!failed.includes(url),json:async()=>url.includes('adverts')?ads:rooms});w.eval(script);await new Promise(resolve=>setTimeout(resolve,20));return {w,d:w.document};}
test('public home shows available rooms and approved offers without a login gate',async()=>{const {d}=await setup();assert.equal(d.querySelectorAll('.campus-card').length,5);assert.ok(!d.getElementById('campusListings').textContent.includes('Filled room'));assert.equal(d.querySelector('.academic-link').getAttribute('href'),'/static/academics.html');});
test('campus, search and category filters combine; clear restores all',async()=>{const {w,d}=await setup();d.getElementById('campus').value='University of Limpopo';d.getElementById('campusSearch').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(d.querySelectorAll('.campus-card').length,3);d.querySelector('[data-category="items"]').click();assert.equal(d.querySelectorAll('.campus-card').length,1);assert.match(d.getElementById('campusListings').textContent,/Biology textbooks/);assert.equal(w.localStorage.getItem('marketCampus'),'University of Limpopo');d.getElementById('search').value='missing';d.getElementById('campusSearch').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.match(d.getElementById('campusListings').textContent,/No listings here yet/);d.getElementById('clearFilters').click();assert.equal(d.querySelectorAll('.campus-card').length,5);});
test('details escape seller content and reject unsafe website links',async()=>{const {d}=await setup();d.querySelector('[data-offer="offer-2"]').click();assert.equal(d.getElementById('offerDialog').open,true);assert.equal(d.getElementById('offerDetails').querySelectorAll('img').length,0);assert.ok(!d.getElementById('offerDetails').innerHTML.includes('href="javascript:'));d.getElementById('closeOffer').click();assert.equal(d.getElementById('offerDialog').open,false);});
test('partial failure keeps available data with a retry; total failure is not an empty market',async()=>{let {d}=await setup(['/marketing/adverts']);assert.equal(d.querySelectorAll('.campus-card').length,2);assert.equal(d.getElementById('retryListings').hidden,false);assert.match(d.getElementById('marketStatus').textContent,/Some listings/);({d}=await setup(['/marketing/adverts','/marketing/listings']));assert.match(d.getElementById('marketStatus').textContent,/could not be loaded/);assert.equal(d.querySelectorAll('.market-empty').length,0);});
